term_palette: 000000;1A1A2E;16213E;0F3460;1B3A57;2D55A0;3A7BC0;4A90E2
term_palette_bright: 111111;1E3A5F;28559E;3474B3;4A90E2;5AA9FF;6FC1FF;8ED4FF
term_foreground: FFFFFF
term_foreground_bright: 4A90E2

/AkmeBSD
    protocol: limine
    path: boot():/kernel.bin

    module_path: boot():/rootfs.img